doctor_mapping = {
    "fungal infection": ("Dermatologist", "Dr. Riya Sharma"),
    "allergy": ("Allergist", "Dr. Aarav Mehta"),
    "gerd": ("Gastroenterologist", "Dr. Neha Kapoor"),
    "chronic cholestasis": ("Hepatologist", "Dr. Vikram Singh"),
    "drug reaction": ("General Physician", "Dr. Priya Verma"),
    "peptic ulcer disease": ("Gastroenterologist", "Dr. Rahul Joshi"),
    "aids": ("Infectious Disease Specialist", "Dr. Karan Malhotra"),
    "diabetes": ("Endocrinologist", "Dr. Sneha Patel"),
    "gastroenteritis": ("General Physician", "Dr. Ananya Rao"),
    "bronchial asthma": ("Pulmonologist", "Dr. Rohan Khanna"),
    "hypertension": ("Cardiologist", "Dr. Mehul Arora"),
    "migraine": ("Neurologist", "Dr. Ishita Jain"),
    "cervical spondylosis": ("Orthopedic", "Dr. Aditya Bansal"),
    "paralysis (brain hemorrhage)": ("Neurologist", "Dr. Yash Kapoor"),
    "jaundice": ("Hepatologist", "Dr. Kavya Sharma"),
    "malaria": ("Infectious Disease Specialist", "Dr. Arjun Nair"),
    "chicken pox": ("General Physician", "Dr. Ritu Malhotra"),
    "dengue": ("General Physician", "Dr. Nitin Verma"),
    "typhoid": ("General Physician", "Dr. Simran Kaur"),
    "hepatitis a": ("Hepatologist", "Dr. Mohit Sinha"),
    "hepatitis b": ("Hepatologist", "Dr. Mohit Sinha"),
    "hepatitis c": ("Hepatologist", "Dr. Mohit Sinha"),
    "hepatitis d": ("Hepatologist", "Dr. Mohit Sinha"),
    "hepatitis e": ("Hepatologist", "Dr. Mohit Sinha"),
    "tuberculosis": ("Pulmonologist", "Dr. Aditi Kapoor"),
    "common cold": ("General Physician", "Dr. Anjali Gupta"),
    "pneumonia": ("Pulmonologist", "Dr. Aditi Kapoor"),
    "dimorphic hemorrhoids(piles)": ("Proctologist", "Dr. Tushar Goel"),
    "heart attack": ("Cardiologist", "Dr. Rajeev Malhotra"),
    "varicose veins": ("Vascular Surgeon", "Dr. Sanya Mehra"),
    "hypothyroidism": ("Endocrinologist", "Dr. Sneha Patel"),
    "hyperthyroidism": ("Endocrinologist", "Dr. Sneha Patel"),
    "arthritis": ("Orthopedic", "Dr. Dev Sharma"),
    "urinary tract infection": ("Urologist", "Dr. Aman Chawla"),
    "psoriasis": ("Dermatologist", "Dr. Riya Sharma"),
    "impetigo": ("Dermatologist", "Dr. Riya Sharma")
}